// es-419 strings of the Automatizacion screens (merged into ES_419). Machine codes (source ids, link grades,
// verdicts, artifact names) are shown verbatim and never translated.
export const AUTOMATION_ES = {
  'auto.nav': 'Automatización',
  'auto.crumb': 'Automatización',
  'auto.title': 'Automatización',
  'auto.intro': 'Cada tipo de caso madura con lo que hace el equipo: primero el copiloto responde, luego propone herramientas, después respuestas. Cuando un tipo completa las tres etapas, el sistema propone un agente.',
  'auto.tabTypes': 'Tipos de caso',
  'auto.tabAgents': 'Agentes',
  'auto.simNotice': 'Réplica de Pulso de la pantalla Automatización (vista previa; no es la plataforma). Son SIMULADOS: {scope}. Las cifras con la insignia «E0 tratado» salen de datos reales tratados (solo agregados). Cada número lleva su origen.',
  'auto.simNoticeNone': 'Réplica de Pulso de la pantalla Automatización (vista previa; no es la plataforma). Ningún dato de esta vista es simulado; cada número lleva su origen.',
  'auto.scope.draft_dispositions': 'los borradores del copiloto',
  'auto.scope.case_types': 'los tipos de caso',
  'auto.scope.stage_history': 'las fechas de cada etapa',
  'auto.scope.cases_today': 'los casos de hoy',
  'auto.scope.agent_runs': 'las ejecuciones del agente',
  'auto.scope.approval': 'la aprobación',
  'auto.scope.publish_staging': 'la publicación a staging',
  'auto.loading': 'Cargando tipos de caso…',
  'auto.unavailable': 'No se pudieron leer los tipos de caso: el modelo de lectura no está disponible.',
  'auto.bannerTitle': 'El sistema propone un agente para {type}',
  'auto.bannerText': 'Completó las tres etapas: el equipo envía {n} de cada 10 borradores del copiloto tal cual o con cambios menores.',
  'auto.bannerButton': 'Ver propuesta',
  'auto.listTitle': 'Tipos de caso',
  'auto.legend0': 'solo personas',
  'auto.legend1': 'responde',
  'auto.legend2': 'propone herramientas',
  'auto.legend3': 'propone respuestas',
  'auto.legendAgent': 'Con agente',
  'auto.colType': 'Tipo de caso',
  'auto.colStage': 'Etapa',
  'auto.colMeasure': 'Lo que mide ahora',
  'auto.colCases': 'Casos hoy',
  'auto.stageN': 'Etapa {n}',
  'auto.withAgent': 'Con agente',
  'auto.agentProposed': 'Agente propuesto',
  'auto.viewSignals': 'Ver señales',
  'auto.measure.draft_accept_100': 'El equipo envía {n} de cada 100 borradores tal cual o con cambios menores',
  'auto.measure.agent_resolved': 'El agente resolvió {r} de {h} y pasó {x} a personas',
  'auto.measure.agent_resolved_nohand': 'El agente resolvió {r} de {h}',
  'auto.measure.tool_use_rate': 'Las herramientas propuestas se usan en {n} de cada 10 casos',
  'auto.measure.repeat_q': 'Una misma pregunta al copiloto se repite en {n} casos',
  'auto.measure.copilot_use': 'Preguntas al copiloto en {n} de cada 10 casos',
  'auto.measure.none': 'Tipo nuevo: lo resuelven personas mientras el copiloto aprende',
  'auto.notComputable': 'No calculable: {reason}',
  'auto.reason.no_draft_rows': 'sin filas de borradores',
  'auto.reason.no_input': 'sin datos de entrada',
  'auto.reason.no_agent_run': 'sin ejecuciones de agente',
  'auto.reason.no_tool_use_events': 'sin eventos de uso de herramientas',
  'auto.reason.no_copilot_query_signature': 'sin firma de pregunta al copiloto',
  'auto.reason.other': 'motivo {reason}',
  'auto.src.e0_treated': 'E0 tratado',
  'auto.src.sim_draft_stream': 'Flujo simulado',
  'auto.src.platform_events': 'Plataforma',
  'auto.simulatedTag': 'SIMULADO',
  'auto.footer': 'Tipos de caso: categorías de los reclamos del banco. Los umbrales para pasar de etapa son una regla del equipo y se editan por la API de configuración.',
  'auto.drawerClose': 'Cerrar',
  'auto.howMatured': 'Cómo maduró',
  'auto.step1': 'El copiloto responde',
  'auto.step2': 'El copiloto propone herramientas',
  'auto.step3': 'El copiloto propone respuestas',
  'auto.stepAgent': 'Agente',
  'auto.since': 'Desde el {date}',
  'auto.proposedToday': 'Propuesto hoy',
  'auto.draftsTitle': 'Borradores del copiloto, últimos 100',
  'auto.draftsAsIs': '{n} tal cual',
  'auto.draftsMinor': '{n} con cambios menores',
  'auto.draftsDiscarded': '{n} descartados',
  'auto.thresholdsTitle': 'Umbrales para pasar de etapa',
  'auto.th1to2': 'Etapa 1 a 2',
  'auto.th2to3': 'Etapa 2 a 3',
  'auto.th3toAgent': 'Etapa 3 a agente',
  'auto.th1to2Rule': 'Una misma pregunta al copiloto se repite en {min} casos',
  'auto.th1to2Today': 'Hoy: {n} casos con preguntas parecidas',
  'auto.th2to3Rule': 'Las herramientas propuestas se usan en {min} de cada 10 casos',
  'auto.th2to3Today': 'Hoy: {n} de cada 10',
  'auto.th3toAgentRule': '{min} de cada 10 borradores se envían tal cual o con cambios menores, en {w} casos seguidos',
  'auto.th3toAgentToday': 'Hoy: {n} de {d}',
  'auto.thMet': 'Cumplido',
  'auto.thNotMet': 'Pendiente',
  'auto.drawerNote': 'Regla del equipo. Las señales salen de lo que registra la plataforma: preguntas al copiloto, herramientas usadas o ignoradas y borradores enviados, editados o descartados.',
  'auto.viewProposal': 'Ver propuesta del agente',
  'auto.noProposal': 'Todavía no hay una propuesta del motor para este tipo de caso.',
  'auto.back': 'Volver a Automatización',
  'auto.propTitle': 'Propuesta del agente para {type}',
  'auto.propSimulated': 'La propuesta, la aprobación y la publicación de esta réplica son SIMULADAS: ningún cambio llega a agent-core ni a la plataforma.',
  'auto.propTarget': 'Objetivo: {target}',
  'auto.propArtifact': 'Artefacto: {from} → {to}',
  'auto.propEval': 'Suite de evaluación: {suite}',
  'auto.propHash': 'Hash del candidato: {hash}',
  'auto.propVerdict': 'Veredicto del libro mayor: {verdict}',
  'auto.propGrade': 'Grado del vínculo: {grade}',
  'auto.propRelated': 'Agentes relacionados: {agents}',
  'auto.propOrigin': 'Origen: {origin} (propuesta del motor, no escrita por una persona)',
  'auto.propAlt': 'Alternativa evaluable hoy: {target} ({artifact}); el copiloto de asesores aún no tiene evaluación verificada',
  'auto.propId': 'Propuesta {id}',
  'auto.propState': 'Estado',
  'auto.propState.proposed': 'Propuesta',
  'auto.propState.approved_simulated': 'Aprobada (simulada)',
  'auto.propState.staged_simulated': 'En staging (simulado)',
  'auto.propRunLink': 'Abrir la ejecución con investigación, diff, compuertas y decisión',
  'auto.approve': 'Aprobar (SIMULADO)',
  'auto.approveNote': 'La aprobación real exige reautenticación (step-up) y queda ligada al hash del candidato; aquí se simula y se registra.',
  'auto.publish': 'Publicar en staging (SIMULADO, doble de Core)',
  'auto.actionFailed': 'No se pudo registrar la acción simulada.',
} as const;
