"""Stack provisioning helpers for the E2E (host side). CLI used by e2e-core/run.ps1:

  python -m codex_standin.stack prepare  --ns NS --dir DIR        test keys + overlay build context (no secrets in git)
  python -m codex_standin.stack overlay  --dir DIR --base IMG --tag TAG
  python -m codex_standin.stack fixtures --ns NS --dir DIR        starts the `e2e-fixtures` DOUBLE container
  python -m codex_standin.stack cleanup  --ns NS --dir DIR [--tag TAG]

Only machine `pulso-dev` (connection passed explicitly). Everything created carries com.pulso.team=claude and
com.pulso.namespace=NS so `local/core/reset.ps1 -Namespace NS -Confirm` removes it."""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

from codex_standin import jwtsvc

PODMAN = r"C:\Users\alexg\AppData\Local\Programs\Podman\podman.exe"
CONNECTION = "pulso-dev"
FIXTURE_ALIAS = "e2e-fixtures"
FIXTURE_PORT = 8700
SERVICE_KID = "e2e-control-api-1"
REPO = Path(__file__).resolve().parents[3]
SECRETS = REPO / "local" / ".secrets"


def podman(*args: str, check: bool = True, input_text: str | None = None) -> str:
    proc = subprocess.run([PODMAN, "--connection", CONNECTION, *args], capture_output=True, text=True,
                          input=input_text, timeout=600)
    if check and proc.returncode != 0:
        raise RuntimeError(f"podman {' '.join(args[:3])} failed: {(proc.stderr or proc.stdout).strip()[:400]}")
    return proc.stdout.strip()


def project(ns: str) -> str:
    return f"pulso-{ns}"


def state_of(ns: str) -> dict[str, Any]:
    return json.loads((SECRETS / ns / "state.json").read_text(encoding="utf-8-sig"))  # type: ignore[no-any-return]


def fixtures_url() -> str:
    return f"http://{FIXTURE_ALIAS}:{FIXTURE_PORT}"


def prepare(ns: str, out: Path) -> dict[str, Any]:
    """Generates THROW-AWAY test keys into `out` (under the git-ignored local/.secrets/<ns>/e2e)."""
    out.mkdir(parents=True, exist_ok=True)
    ctx = out / "context"
    ctx.mkdir(exist_ok=True)
    control = jwtsvc.Ed25519PrivateKey.generate()
    (ctx / "service.json").write_text(json.dumps({"keys": {SERVICE_KID: {
        "iss": "control-api", "aud": "core-bridge", "key": jwtsvc.public_of(control)}}}), encoding="ascii")
    (ctx / "budgets.json").write_text(json.dumps({
        "bud-e2e": {"cost_usd_max": "5", "tokens_max": 200000, "jobs_max": 50}}), encoding="ascii")
    endpoints = {"pulso-evolution-llm": {"base_url": fixtures_url() + "/llm/v1", "api_key_env": "E2E_LLM_KEY"}}
    (ctx / "Dockerfile").write_text("\n".join([
        "# E2E config overlay: SAME runtime layers, only env + test key files (never pushed, removed by cleanup).",
        "ARG BASE", "FROM ${BASE}", "USER 0", "COPY service.json budgets.json /opt/e2e/",
        "RUN chown -R 10001:10001 /opt/e2e && chmod 640 /opt/e2e/*", "USER 10001",
        "ENV PULSO_SERVICE_KEYS=/opt/e2e/service.json"
        " PULSO_EVAL_BUDGETS=/opt/e2e/budgets.json E2E_LLM_KEY=scripted-not-a-secret",
        "ENV LLM_ENDPOINTS='" + json.dumps(endpoints, separators=(",", ":")) + "'",
        "LABEL com.pulso.e2e.overlay=true", ""]), encoding="ascii")
    keys = {"service_kid": SERVICE_KID, "service_seed": jwtsvc.seed_of(control), "namespace": ns, "fixtures_url": fixtures_url()}
    (out / "e2e-keys.json").write_text(json.dumps(keys), encoding="ascii")
    return keys


def overlay(ctx_dir: Path, base: str, tag: str) -> str:
    podman("build", "--build-arg", f"BASE={base}", "-t", tag, str(ctx_dir / "context"))
    return podman("image", "inspect", tag, "--format", "{{.Id}}")


def read_volume_file(ns: str, name: str) -> str:
    return podman("exec", f"{project(ns)}-core-runtime-1", "cat", f"/run/pulso-keys/{name}")


def verify_keys(ns: str, keys: dict[str, Any]) -> dict[str, Any]:
    cb = json.loads(read_volume_file(ns, "bridge-callback.json"))
    cb_pub = jwtsvc.public_of(jwtsvc.private_from_seed(cb["key"]))
    exp_keys = json.loads(read_volume_file(ns, "service.json"))["keys"]
    # core-keygen registers the exporter keys with iss `pulso-exporter`, but the exporter signs `iss=core-bridge`
    # (A03): the receiver double registers what the exporter REALLY sends. Reported as a gap (keygen vs exporter).
    ingest_keys = {kid: {**v, "iss": "core-bridge"} for kid, v in exp_keys.items() if kid.startswith("exporter-")}
    # the executor (lab-broker class iii) key is generated by core-keygen; only its PUBLIC half is read
    trust = json.loads(read_volume_file(ns, "lab-broker-trust.json"))["keys"]
    return {
        "ring": {cb["kid"]: ["core-bridge", "control-api", cb_pub],
                 **{kid: [v["iss"], v["aud"], v["key"]] for kid, v in trust.items()}},
        "ingest": {"keys": ingest_keys, "binding_ref": "binding-local", "tenant_id": "tenant-local"}}


GRANTS_WORKAROUND = (
    "GRANT SELECT, INSERT, UPDATE, DELETE ON runs, run_idempotency, turn_leases, turn_results, usage, handoffs, outbox"
    " TO core_app; GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO core_app;")


def apply_grants_workaround(ns: str) -> None:
    """`agentcore migrate --app-role` grants core_app only audit_events (+ registry tables through the registry
    schema): the engine tables (`runs`, ...) stay owner-only and the first `POST /v1/runs` dies with
    InsufficientPrivilege. local/core/init/*.sql does not grant them either. DECLARED double in the report
    (`db_grants:workaround`) until L8 adds the grants to its init SQL."""
    pg = f"{project(ns)}-core-postgres-1"
    podman("exec", pg, "psql", "-U", "postgres", "-d", "core_runtime", "-v", "ON_ERROR_STOP=1", "-c",
           GRANTS_WORKAROUND)
    # 15-eval-grants.sql grants ALL ON ALL TABLES to core_eval_app but no sequence: the first evaluation run dies
    # with `permission denied for sequence runs_run_seq_seq` (arms report failed_infra infra_InsufficientPrivilege).
    podman("exec", pg, "psql", "-U", "postgres", "-d", "core_eval", "-v", "ON_ERROR_STOP=1", "-c",
           "GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO core_eval_app;")


def start_fixtures(ns: str, ctx_dir: Path) -> dict[str, Any]:
    st = state_of(ns)
    apply_grants_workaround(ns)
    keys = json.loads((ctx_dir / "e2e-keys.json").read_text(encoding="ascii"))
    sim_image = next(line.split("=", 1)[1] for line in (SECRETS / ns / "ports.env").read_text().splitlines()
                     if line.startswith("PULSO_SIM_IMAGE="))
    name = f"{project(ns)}-{FIXTURE_ALIAS}-1"
    port = _free_port()
    podman("rm", "-f", name, check=False)
    podman("create", "--name", name, "--network", f"{project(ns)}_core-net", "--network-alias", FIXTURE_ALIAS,
           "--cgroups=disabled", "--pids-limit=0", "--label", "com.pulso.team=claude", "--label",
           f"com.pulso.namespace={ns}", "--label", "com.pulso.role=double", "--label",
           "com.pulso.piece=e2e-fixtures", "-p", f"127.0.0.1:{port}:{FIXTURE_PORT}",
           "-e", "PYTHONPATH=/opt/e2e:/sim:/opt/pulso/lib", "-e", f"E2E_PORT={FIXTURE_PORT}",
           "-e", "E2E_VERIFY_KEYS=" + json.dumps(verify_keys(ns, keys), separators=(",", ":")),
           "--entrypoint", json.dumps(["python", "-m", "codex_standin.serve"]), sim_image)
    stage = Path(tempfile.mkdtemp(prefix="e2e-stage-"))
    try:
        shutil.copytree(Path(__file__).parent, stage / "opt" / "e2e" / "codex_standin",
                        ignore=shutil.ignore_patterns("__pycache__"))
        shutil.copytree(REPO / "platform-sim" / "ingest_fixture", stage / "sim" / "ingest_fixture",
                        ignore=shutil.ignore_patterns("__pycache__"))
        podman("cp", str(stage) + "\\.", f"{name}:/")
    finally:
        shutil.rmtree(stage, ignore_errors=True)
    podman("start", name)
    info = {"container": name, "host_port": port, "url": f"http://127.0.0.1:{port}", "internal_url": fixtures_url(),
            "namespace": ns, "connection": CONNECTION, "ports": st["ports"], "image": st["image"],
            "expected_image_digest": st["expected_image_digest"], "project": project(ns)}
    (ctx_dir / "e2e-env.json").write_text(json.dumps(info), encoding="ascii")
    return info


def _free_port() -> int:
    import socket
    with socket.socket() as s:
        s.bind(("127.0.0.1", 0))
        return int(s.getsockname()[1])


def cleanup(ns: str, ctx_dir: Path | None, tag: str | None) -> None:
    podman("rm", "-f", f"{project(ns)}-{FIXTURE_ALIAS}-1", check=False)
    if tag:
        ident = podman("image", "inspect", tag, "--format", "{{.Id}}", check=False).replace("sha256:", "")[:12]
        podman("rmi", "-f", tag, check=False)
        if ident:  # the doubles image start.ps1 builds FROM the overlay (never shared with other namespaces)
            podman("rmi", "-f", f"localhost/pulso-platform-sim:{ident}", check=False)
    if ctx_dir and ctx_dir.exists():
        shutil.rmtree(ctx_dir, ignore_errors=True)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("cmd", choices=["prepare", "overlay", "fixtures", "cleanup"])
    ap.add_argument("--ns", default="")
    ap.add_argument("--dir", default="")
    ap.add_argument("--base", default="")
    ap.add_argument("--tag", default="")
    a = ap.parse_args(argv)
    d = Path(a.dir) if a.dir else None
    if a.cmd == "prepare":
        assert d is not None
        prepare(a.ns, d)
        print("prepared")
    elif a.cmd == "overlay":
        assert d is not None
        print("overlay_id=" + overlay(d, a.base, a.tag))
    elif a.cmd == "fixtures":
        assert d is not None
        print(json.dumps(start_fixtures(a.ns, d)))
    else:
        cleanup(a.ns, d, a.tag or None)
        print("cleaned")
    return 0


if __name__ == "__main__":
    sys.exit(main())
