"""Double of the standalone llm-gateway that follows its DOCUMENTED contract (docs/LLM_GATEWAY_ADOPTION_CLAUDE.md
section 1, llm-gateway api/openapi.yaml). No real gateway binary or image exists in this toolchain (no Go, no
published image), so this is an `httpx.MockTransport` handler, never presented as the real service.

Contract points reproduced: check order method -> auth -> content-type -> body size -> body decode; closed request
contract (unknown fields -> 400, so `stream` is rejected); decimal-string prices; closed label keys; cost computed
from the price the CALLER sent (this is exactly why the runtime pins its own price table); typed error bodies that
carry tokens/cost for `invalid_output` and `refused`; no provider cost is ever read."""

from __future__ import annotations

import json
from collections.abc import Callable
from decimal import ROUND_HALF_UP, Decimal
from typing import Any

import httpx

REQUEST_KEYS = {"prompt", "inputs", "schema", "profile", "labels"}
PROFILE_KEYS = {"endpoint_alias", "model", "temperature", "max_tokens", "timeout_s", "structured", "price"}
LABEL_KEYS = {"prompt", "model_profile", "run_id", "turn_id", "session_id", "release", "agent"}
MAX_BODY = 1 << 20


def cost_of(tokens_in: int, tokens_out: int, price: dict[str, str]) -> str:
    total = (Decimal(tokens_in) * Decimal(price["input_per_mtok"])
             + Decimal(tokens_out) * Decimal(price["output_per_mtok"])) / Decimal(1_000_000)
    return format(total.quantize(Decimal("0.000001"), rounding=ROUND_HALF_UP), "f")


def _err(status: int, kind: str, **extra: Any) -> httpx.Response:
    return httpx.Response(status, json={"error": {"kind": kind, "message": "generated by the gateway", **extra}})


def ok(tokens_in: int = 1000, tokens_out: int = 500, output: Any = None, model: str = "reported-model",
       usage_known: bool = True) -> Callable[[dict[str, Any]], httpx.Response]:
    def respond(req: dict[str, Any]) -> httpx.Response:
        tin, tout = (tokens_in, tokens_out) if usage_known else (0, 0)
        return httpx.Response(200, json={
            "output": {"kind": "final", "output": {}} if output is None else output, "model": model,
            "tokens_in": tin, "tokens_out": tout,
            "cost_usd": cost_of(tin, tout, req["profile"]["price"]) if usage_known else "0.000000",
            "usage_known": usage_known})
    return respond


def failure(status: int, kind: str, tokens_in: int | None = None,
            tokens_out: int | None = None) -> Callable[[dict[str, Any]], httpx.Response]:
    def respond(req: dict[str, Any]) -> httpx.Response:
        extra: dict[str, Any] = {}
        if tokens_in is not None and tokens_out is not None:
            extra = {"model": "reported-model", "tokens_in": tokens_in, "tokens_out": tokens_out,
                     "cost_usd": cost_of(tokens_in, tokens_out, req["profile"]["price"])}
        return _err(status, kind, **extra)
    return respond


def raising(exc: Exception) -> Callable[[dict[str, Any]], httpx.Response]:
    def respond(req: dict[str, Any]) -> httpx.Response:
        raise exc
    return respond


class GatewayDouble:
    """`script` is consumed one entry per accepted generate call; the last entry repeats."""

    def __init__(self, *script: Callable[[dict[str, Any]], httpx.Response], tokens: tuple[str, ...] = ("tok-ok",),
                 min_delay_s: float = 0.0) -> None:
        self.script = list(script) or [ok()]
        self.tokens = set(tokens)
        self.requests: list[dict[str, Any]] = []     # accepted, decoded generate bodies
        self.raw: list[httpx.Request] = []           # every request incl. probes/rejections
        self.probes = 0
        self.delay = min_delay_s
        self._n = 0

    def client(self) -> httpx.Client:
        return httpx.Client(transport=httpx.MockTransport(self.handle))

    def handle(self, request: httpx.Request) -> httpx.Response:
        self.raw.append(request)
        if request.url.path != "/v1/generate":
            return _err(404, "not_found")
        if request.method != "POST":
            return _err(405, "bad_request")
        auth = request.headers.get("authorization", "")
        if not auth.startswith("Bearer ") or auth[7:] not in self.tokens:
            return _err(401, "unauthorized")
        if "application/json" not in request.headers.get("content-type", ""):
            return _err(415, "unsupported_media_type")
        if len(request.content) > MAX_BODY:
            return _err(413, "payload_too_large")
        try:
            body = json.loads(request.content)
        except ValueError:
            self.probes += 1
            return _err(400, "bad_request")  # the free authenticated probe: valid token + empty body
        problem = self._validate(body)
        if problem:
            self.probes += 1
            return _err(400, "bad_request")
        self.requests.append(body)
        if self.delay:
            import time
            time.sleep(self.delay)
        index = min(self._n, len(self.script) - 1)
        self._n += 1
        return self.script[index](body)

    @staticmethod
    def _validate(body: Any) -> str | None:
        if not isinstance(body, dict) or not set(body) <= REQUEST_KEYS or "prompt" not in body \
                or "profile" not in body:
            return "shape"
        profile = body["profile"]
        if not isinstance(profile, dict) or not set(profile) <= PROFILE_KEYS:
            return "profile"
        price = profile.get("price")
        if not isinstance(price, dict) or set(price) != {"input_per_mtok", "output_per_mtok"}:
            return "price"
        for value in price.values():
            if not isinstance(value, str) or not (0 <= Decimal(value) <= 1_000_000):
                return "price value"
        if not 1 <= int(profile["max_tokens"]) <= 1_000_000 or not 1 <= int(profile.get("timeout_s", 8)) <= 300:
            return "range"
        if not set(body.get("labels", {})) <= LABEL_KEYS:
            return "labels"
        return None
