"""Render db/sql/*.sql from db/catalog.py.  Usage: python db/gen_ddl.py  (rewrites the committed files)."""

from __future__ import annotations

import sys
from pathlib import Path

import catalog as c

HEADER = "-- GENERATED by db/gen_ddl.py from db/catalog.py. Do not edit by hand.\n"


def _table(schema: str, table: str, cols: list[tuple[str, str]]) -> str:
    body = [f"    {n} {t}" for n, t in cols]
    body += ["    _batch_id text", "    _source_file text", "    _ingested_at timestamptz NOT NULL DEFAULT now()"]
    return (f"CREATE TABLE IF NOT EXISTS {schema}.{table} (\n" + ",\n".join(body) + "\n);\n"
            f"CREATE INDEX IF NOT EXISTS {table}_batch_ix ON {schema}.{table} (_batch_id);\n")


def _schema_file(schema: str, note: str) -> str:
    out = [HEADER, f"-- {note}\n"]
    out += [_table(schema, t, cols) for t, cols in c.SCHEMAS[schema].items()]
    if schema == "product":
        out.append("CREATE UNIQUE INDEX IF NOT EXISTS event_log_sequence_ux ON product.event_log (sequence);\n"
                   "-- watermark: the monitor reads event_log WHERE sequence > :last ORDER BY sequence.\n")
    return "\n".join(out)


def _roles() -> str:
    out = [HEADER, "-- Roles are NOLOGIN here; bootstrap sets LOGIN and the password from secrets (never in SQL).\n"]
    roles = [*c.READER_ROLE.values(), c.LOADER_ROLE, c.APP_ROLE]
    for r in roles:
        out.append(f"DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{r}') "
                   f"THEN CREATE ROLE {r} NOLOGIN; END IF; END $$;")
    out.append("")
    for s in c.SCHEMAS:
        out.append(f"CREATE SCHEMA IF NOT EXISTS {s};")
    out.append("CREATE SCHEMA IF NOT EXISTS pulso;  -- engine-owned tables (migrations/), written by pulso_app only")
    out.append("")
    for r in c.READER_ROLE.values():
        out.append(f"ALTER ROLE {r} SET default_transaction_read_only = on;")
    return "\n".join(out) + "\n"


def _grants() -> str:
    out = [HEADER, "-- Column-level, read-only. Sensitive columns (free text, names, contact data) are not granted;",
           "-- product columns are already limited to the exporter allow-list. No reader can write.\n"]
    for s, tables in c.SCHEMAS.items():
        r = c.READER_ROLE[s]
        out.append(f"GRANT USAGE ON SCHEMA {s} TO {r}, {c.LOADER_ROLE};")
        out.append(f"REVOKE ALL ON SCHEMA {s} FROM PUBLIC;")
        for t, cols in tables.items():
            readable = [n for n, _ in cols if not c.is_sensitive(t, n, s)]
            readable += list(c.LINEAGE_NAMES)
            out.append(f"GRANT SELECT ({', '.join(readable)}) ON {s}.{t} TO {r};")
            out.append(f"GRANT SELECT, INSERT, DELETE ON {s}.{t} TO {c.LOADER_ROLE};")
        out.append("")
    out.append(f"GRANT USAGE, CREATE ON SCHEMA pulso TO {c.APP_ROLE};")
    out.append(f"GRANT USAGE ON SCHEMA product, augmented TO {c.APP_ROLE};  -- app reads through the *_ro roles")
    return "\n".join(out) + "\n"


def render_all() -> dict[str, str]:
    return {
        "001_roles_schemas.sql": _roles(),
        "010_raw.sql": _schema_file("raw", "Original datasets, lossless, loaded by the user: E0 (9 tables; evaluator "
                                    "tables labels/timeline and pseudonym_map are never created) and 13 bank tables."),
        "020_augmented.sql": _schema_file("augmented", "Canonical layer (dbt canonical models)."),
        "030_product.sql": _schema_file("product", "Support-platform replica, exporter allow-list columns only."),
        "090_grants.sql": _grants(),
    }


if __name__ == "__main__":
    out = Path(__file__).parent / "sql"
    for name, text in render_all().items():
        (out / name).write_text(text, encoding="utf-8", newline="\n")
    print("wrote", len(render_all()), "files", file=sys.stderr)
