"""GT05 report generator: writes docs/reports/gates/gt05/gt05-report.md and gate-result.json from the manifest's artifacts.

Every label, digest, count and finding is read from an artifact (Rust-steps report, default report, run record, review logs,
gate evaluation). A missing artifact is printed as MISSING, never filled in. Do not edit the output by hand.
Usage: python gt05_report.py --manifest M.json [--out gt05-report.md] [--result gate-result.json] [--steps-exe EXE]
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
sys.path.insert(0, str(HERE))
import gt05_gate as gate  # noqa: E402
import gt0_gate  # noqa: E402


def _c(x) -> str:
    return str(x).replace("|", "\\|").replace("\n", " ") if x is not None else ""


def table(head: list, rows: list) -> list:
    out = ["| " + " | ".join(head) + " |", "|" + "|".join("---" for _ in head) + "|"]
    out += ["| " + " | ".join(_c(c) for c in r) + " |" for r in rows]
    return out + [""]


def _art(base: Path, m: dict, key: str):
    rel = (m.get("artifacts") or {}).get(key)
    if not isinstance(rel, str):
        return None, f"MISSING: no {key} in the manifest"
    doc, prob = gt0_gate._json(base / rel)
    return doc, (f"MISSING: {rel}" if prob and prob.startswith("missing") else (f"UNREADABLE: {rel}" if prob else None))


def _residuals(reviews: Path) -> list:
    rows = []
    for p in sorted(reviews.glob("*.review.json")) if reviews.is_dir() else []:
        try:
            log = json.loads(p.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            continue
        for f in log.get("findings", []):
            if str(f.get("id", "")).startswith("CRV1-RES") and f.get("status") == "accepted":
                rows.append([f["id"], f.get("summary"), f.get("owner"), f.get("tracking")])
    return rows


def evaluate(manifest: Path, steps_exe=None, gt0_evaluator=None) -> list:
    return gate.evaluate(manifest, repo=ROOT, steps_exe=steps_exe, gt0_evaluator=gt0_evaluator)


def generate(manifest: Path, steps_exe=None, gt0_evaluator=None, results=None) -> str:
    manifest = Path(manifest)
    m, prob = gt0_gate._json(manifest)
    if prob:
        return f"# GT05 gate report\n\nMISSING: manifest {manifest.name}\n"
    base = manifest.parent
    results = results if results is not None else evaluate(manifest, steps_exe, gt0_evaluator)
    ok = all(r["ok"] for r in results)
    rust, n_rust = _art(base, m, "rust_report")
    default, n_def = _art(base, m, "default_report")
    run, n_run = _art(base, m, "run")
    ratchet, n_rat = _art(base, m, "ratchet_receipt")
    L = ["# GT05 gate report (DEMO-1a, Rust steps called by the Python host)", "",
         "Generated by `scripts/gov/gt05_report.py` from the artifacts named in the gate manifest. Do not edit by hand: "
         "rerun the collector, the gate and this generator.", "",
         "## 1. Verdict and scope", "", f"Verdict: {'PASS' if ok else 'FAIL'}", ""]
    L += [f"- items passing: {sum(r['ok'] for r in results)} of {len(results)}; failing: "
          + (", ".join(r["item"] for r in results if not r["ok"]) or "none")]
    if rust:
        L += [f"- Rust-steps report: label {rust.get('label')}, host {rust.get('host')}, target {rust.get('target')}, "
              f"quality_claims {rust.get('quality_claims')}, sha {rust.get('sha')}"]
    else:
        L += [f"- {n_rust}"]
    if run:
        L += [f"- run record: mode {run.get('mode')}, exit_code {run.get('exit_code')}, {run.get('calls')} replay calls, "
              f"{run.get('misses')} misses, steps_cli sha256 {str(run.get('steps_exe_sha256'))[:12]}"]
    else:
        L += [f"- {n_run}"]
    L += [""]
    L += ["## 2. Gate items", ""] + table(["item", "result", "detail"],
                                          [[r["item"], ("MISSING" if str(r["detail"]).startswith("MISSING") else "PASS" if r["ok"] else "FAIL"), r["detail"]]
                                           for r in results])
    L += ["## 3. The five flips (Rust-steps run)", ""]
    if rust:
        rows = []
        for sid, n in gate.FLIPS:
            s = gate._step(rust, sid) or {}
            rows.append([n, sid, s.get("status"), s.get("host"), s.get("semantics"), s.get("steps_label"),
                         str(s.get("steps_exe_sha256", ""))[:12], s.get("steps_fallback", "")])
        L += table(["n", "step", "status", "host", "semantics", "steps label", "steps_cli sha256", "fallback"], rows)
    else:
        L += [n_rust, ""]
    L += ["## 4. Ten-step table (Rust-steps run)", ""]
    if rust:
        L += table(["id", "status", "data class", "host", "receipt provider", "semantics", "error"],
                   [[s.get("id"), s.get("status"), s.get("data_class"), s.get("host"), (s.get("receipt") or {}).get("provider"),
                     s.get("semantics"), s.get("error")] for s in rust.get("steps") or []])
    else:
        L += [n_rust, ""]
    L += ["## 5. Default run (ratchet default unchanged)", ""]
    if default:
        L += table(["id", "status", "data class", "Rust keys present"],
                   [[s.get("id"), s.get("status"), s.get("data_class"), ", ".join(k for k in gate.RUST_KEYS if k in s) or "none"]
                    for s in default.get("steps") or []])
    else:
        L += [n_def, ""]
    L += ["## 6. Ratchet tests (RG-1)", ""]
    if ratchet:
        L += [f"- command: `{ratchet.get('command')}`", f"- exit {ratchet.get('exit_code')}, passed {ratchet.get('passed')}, "
              f"failed {ratchet.get('failed')}, skipped {ratchet.get('skipped')}", ""]
    else:
        L += [n_rat, ""]
    L += ["## 7. Residual risks kept by CRV1", ""]
    res = _residuals(base / m.get("reviews_dir", "docs/reviews/claude"))
    L += table(["id", "risk", "owner", "tracking"], res) if res else ["MISSING: no CRV1 residual findings in the review logs", ""]
    return "\n".join(L).rstrip() + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--manifest", required=True)
    ap.add_argument("--out")
    ap.add_argument("--result")
    ap.add_argument("--steps-exe")
    a = ap.parse_args(argv)
    manifest = Path(a.manifest)
    res = evaluate(manifest, a.steps_exe)
    out = Path(a.out) if a.out else manifest.parent / "gt05-report.md"
    out.write_text(generate(manifest, a.steps_exe, results=res), encoding="utf-8", newline="\n")
    rpath = Path(a.result) if a.result else manifest.parent / "gate-result.json"
    ok = all(r["ok"] for r in res)
    rpath.write_text(json.dumps({"schema": "gt05-gate-result/v1", "verdict": "pass" if ok else "fail", "items": res}, indent=1) + "\n",
                     encoding="utf-8", newline="\n")
    print(f"wrote {out} and {rpath}: {'pass' if ok else 'fail'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
