"""GT0 report generator: writes docs/reports/gates/gt0-report.md from the manifest's artifacts and the gate result.

Every number, label, digest and finding in the report is read from an artifact (receipts, the engine-run report, the replay
record, the live-window log, FREEZE.json, review logs). A missing artifact is printed as MISSING, never filled in.
Usage: python gt0_report.py --manifest M.json [--out docs/reports/gates/gt0-report.md]
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
sys.path.insert(0, str(HERE))
import gt0_gate as gate  # noqa: E402

DEFAULT_OUT = ROOT / "docs" / "reports" / "gates" / "gt0-report.md"


def _c(x) -> str:
    return str(x).replace("|", "\\|").replace("\n", " ") if x is not None else ""


def table(head: list, rows: list) -> list:
    out = ["| " + " | ".join(head) + " |", "|" + "|".join("---" for _ in head) + "|"]
    out += ["| " + " | ".join(_c(c) for c in r) + " |" for r in rows]
    return out + [""]


def _art(base: Path, m: dict, key: str):
    """(doc, missing-note). The note is MISSING: <file> when the artifact is absent or unreadable."""
    rel = (m.get("artifacts") or {}).get(key)
    if not isinstance(rel, str):
        return None, f"MISSING: no {key} in the manifest"
    doc, prob = gate._json(base / rel)
    return doc, (f"MISSING: {rel}" if prob and prob.startswith("missing") else (f"UNREADABLE: {rel}" if prob else None))


def generate(manifest: Path) -> str:
    manifest = Path(manifest)
    m, prob = gate._json(manifest)
    if prob:
        return f"# GT0 gate report\n\nMISSING: manifest {manifest.name}\n"
    base = manifest.parent
    results = gate.evaluate(manifest, repo=ROOT)
    ok = all(r["ok"] for r in results)
    report, n_rep = _art(base, m, "report")
    replay, n_rpl = _art(base, m, "replay")
    live, n_live = _art(base, m, "live_log")
    g0p, n_g0p = _art(base, m, "g0p")
    trn, n_trn = _art(base, m, "trn0")
    cap, n_cap = _art(base, m, "capacity")
    L = ["# GT0 gate report (DEMO-0)", "",
         "Generated by `scripts/gov/gt0_report.py` from the artifacts named in the gate manifest. Do not edit by hand: "
         "rerun the collector, the gate and this generator.", "",
         "## 1. Verdict and scope", "", f"Verdict: {'PASS' if ok else 'FAIL'}", ""]
    if report:
        L += [f"- label {report.get('label')}, host {report.get('host')}, target {report.get('target')}, "
              f"contract_revision {report.get('contract_revision')}, sha {report.get('sha')}",
              f"- quality_claims: {report.get('quality_claims')}; gate judge {(report.get('gate') or {}).get('judge')}, "
              f"gate verdict {(report.get('gate') or {}).get('verdict')}"]
        for o in report.get("overrides") or []:
            who = "simulated human" if o.get("simulated") else o.get("by")
            L.append(f"- OVERRIDE of the {o.get('of')} verdict {o.get('verdict')!r} by a {who} ({o.get('label')}): {o.get('reason')}")
        L.append("")
    else:
        L += [n_rep, ""]
    L += ["## 2. Gate items", ""] + table(["item", "result", "detail"],
                                          [[r["item"], "PASS" if r["ok"] else "FAIL", r["detail"]] for r in results])
    L += ["## 3. Doubles (generated by the engine, not hand-written)", ""]
    if report:
        L += table(["part", "status", "provider", "data class", "observed"],
                   [[d.get("part"), d.get("status"), d.get("provider") or d.get("price_source"), d.get("data_class"),
                     "yes" if d.get("observed") else ""] for d in report.get("doubles") or []])
    else:
        L += [n_rep, ""]
    L += ["## 4. Ten-step table", ""]
    if report:
        L += table(["id", "status", "data class", "host", "receipt provider", "scanner id", "model"],
                   [[s.get("id"), s.get("status"), s.get("data_class"), s.get("host"), (s.get("receipt") or {}).get("provider"),
                     (s.get("receipt") or {}).get("scanner_id"), s.get("model")] for s in report.get("steps") or []])
    else:
        L += [n_rep, ""]
    L += ["## 5. Replay", ""]
    if replay:
        L += [f"- run id {replay.get('run_id')}: {replay.get('calls')} calls, {replay.get('misses')} digest misses",
              f"- fixtures digest {replay.get('fixtures_digest')}", f"- report bytes {replay.get('report_sha256')}", ""]
    else:
        L += [n_rpl, ""]
    L += ["## 6. Live windows", ""]
    if live:
        L += table(["window", "kind", "calls", "minutes", "scanner rejections", "responders"],
                   [[w.get("id"), w.get("kind"), w.get("calls"), w.get("minutes"), w.get("scanner_rejections"), w.get("responders")]
                    for w in live.get("windows") or []])
    else:
        L += [n_live, ""]
    L += ["## 7. Honesty tests 1-8 against this report", ""]
    if report and replay:
        hr = gate.honesty_results(report, replay)
        L += table(["test", "rule", "violations"], [[t, r, len(hr[t])] for t, r in gate.HONESTY_TESTS.items()]
                   + [["G1/S1 and other", "-", len(hr["other"])]])
    else:
        L += [n_rep or n_rpl, ""]
    L += ["## 8. Frozen contracts", ""]
    pin, p = gate._json(ROOT / "contracts" / "engine-run" / "FREEZE.json")
    if pin:
        for cid, c in sorted(pin["contracts"].items()):
            L.append(f"- {cid} ({c['status']}): {c['digest']}; files: " + ", ".join(sorted(c["files"])))
        L.append("")
    else:
        L += [f"MISSING: FREEZE.json ({p})", ""]
    L += ["## 9. Receipts", ""]
    if g0p:
        L += [f"- G0p: verdict {g0p.get('verdict')}, head {g0p.get('head_sha')}, base {g0p.get('base_ref')}, "
              f"Rust files changed {len(g0p.get('rust_files_changed') or [])}; note: {g0p.get('notes')}"]
        L += [f"  - leg {k}: {v.get('status')} (`{v.get('command')}`)" for k, v in (g0p.get("legs") or {}).items()]
    else:
        L.append(f"- G0p: {n_g0p}")
    if trn:
        L.append(f"- TRN0: verdict {trn.get('verdict')}, " + "; ".join(
            f"PR {p_.get('n')}: lanes {','.join(p_.get('lanes', []))}, {p_.get('lane_hours')} lane-hours, W0 receipt {p_.get('w0_receipt')}"
            for p_ in trn.get("prs") or []))
    else:
        L.append(f"- TRN0: {n_trn}")
    crv = next((r for r in results if r["item"] == "crv0"), None)
    L += [f"- CRV0 closure: {'closed' if crv and crv['ok'] else 'NOT closed'}: {crv['detail'] if crv else ''}", ""]
    L += ["## 10. Capacity re-baseline", ""]
    L += [f"- baseline {cap.get('baseline_lane_hours_per_session')} lane-hours per session from {len(cap.get('sessions') or [])} sessions", ""] \
        if cap else [n_cap, ""]
    L += ["## 11. Open risks (open review findings and failing items)", ""]
    rv = base / m.get("reviews_dir", "docs/reviews/claude")
    opens = []
    for path in sorted(rv.glob("*.review.json")) if rv.is_dir() else []:
        doc, _ = gate._json(path)
        for f in (doc or {}).get("findings", []):
            if f.get("status") == "open":
                opens.append(f"- {f.get('id')} ({','.join(doc.get('wps', []))}): {f.get('summary')}")
    L += opens + [f"- gate item {r['item']} fails: {r['detail']}" for r in results if not r["ok"]]
    if not opens and ok:
        L.append("- none recorded")
    return "\n".join(L).rstrip() + "\n"


def write(manifest: Path, out: Path = DEFAULT_OUT) -> Path:
    out = Path(out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(generate(manifest), encoding="utf-8", newline="\n")
    return out


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--manifest", required=True)
    ap.add_argument("--out", default=str(DEFAULT_OUT))
    a = ap.parse_args(argv)
    print(f"wrote {write(Path(a.manifest), Path(a.out))}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
