-- GENERATED by db/gen_ddl.py from db/catalog.py. Do not edit by hand.

-- Roles are NOLOGIN here; bootstrap sets LOGIN and the password from secrets (never in SQL).

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'pulso_raw_ro') THEN CREATE ROLE pulso_raw_ro NOLOGIN; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'pulso_augmented_ro') THEN CREATE ROLE pulso_augmented_ro NOLOGIN; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'pulso_product_ro') THEN CREATE ROLE pulso_product_ro NOLOGIN; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'pulso_loader') THEN CREATE ROLE pulso_loader NOLOGIN; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'pulso_app') THEN CREATE ROLE pulso_app NOLOGIN; END IF; END $$;

CREATE SCHEMA IF NOT EXISTS raw;
CREATE SCHEMA IF NOT EXISTS augmented;
CREATE SCHEMA IF NOT EXISTS product;
CREATE SCHEMA IF NOT EXISTS pulso;  -- engine-owned tables (migrations/), written by pulso_app only

ALTER ROLE pulso_raw_ro SET default_transaction_read_only = on;
ALTER ROLE pulso_augmented_ro SET default_transaction_read_only = on;
ALTER ROLE pulso_product_ro SET default_transaction_read_only = on;
