-- GENERATED by db/gen_ddl.py from db/catalog.py. Do not edit by hand.

-- Original datasets, lossless, loaded by the user: E0 (9 tables; evaluator tables labels/timeline and pseudonym_map are never created) and 13 bank tables.

CREATE TABLE IF NOT EXISTS raw.e0_case (
    case_id text,
    customer_id text,
    opened_at timestamptz,
    channel text,
    language text,
    origin text,
    topic text,
    complaint_id text,
    priority text,
    sla_due_at timestamptz,
    assigned_analyst_id text,
    _batch_id text,
    _source_file text,
    _ingested_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS e0_case_batch_ix ON raw.e0_case (_batch_id);

CREATE TABLE IF NOT EXISTS raw.e0_turn (
    turn_id text,
    case_id text,
    event_time timestamptz,
    author_role text,
    author_id text,
    text text,
    language text,
    from_suggestion_id text,
    evidence_ids jsonb,
    text_source text,
    _batch_id text,
    _source_file text,
    _ingested_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS e0_turn_batch_ix ON raw.e0_turn (_batch_id);

CREATE TABLE IF NOT EXISTS raw.e0_identity_check (
    check_id text,
    case_id text,
    started_at timestamptz,
    ended_at timestamptz,
    actor_role text,
    actor_id text,
    channel_session text,
    questions jsonb,
    questions_version text,
    correct integer,
    result text,
    attempt integer,
    policy_rule_id text,
    trigger text,
    _batch_id text,
    _source_file text,
    _ingested_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS e0_identity_check_batch_ix ON raw.e0_identity_check (_batch_id);

CREATE TABLE IF NOT EXISTS raw.e0_routing_step (
    step_id text,
    case_id text,
    event_time timestamptz,
    tier text,
    component_id text,
    component_version text,
    outcome text,
    reason_code text,
    policy_rule_id text,
    confidence double precision,
    inputs_used jsonb,
    handoff jsonb,
    _batch_id text,
    _source_file text,
    _ingested_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS e0_routing_step_batch_ix ON raw.e0_routing_step (_batch_id);

CREATE TABLE IF NOT EXISTS raw.e0_copilot_query (
    query_id text,
    case_id text,
    analyst_id text,
    event_time timestamptz,
    question_text text,
    query_signature text,
    tables_read jsonb,
    columns_read jsonb,
    answered_by text,
    answer text,
    sent_to_chat boolean,
    _batch_id text,
    _source_file text,
    _ingested_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS e0_copilot_query_batch_ix ON raw.e0_copilot_query (_batch_id);

CREATE TABLE IF NOT EXISTS raw.e0_tool_call (
    call_id text,
    case_id text,
    event_time timestamptz,
    actor_role text,
    actor_id text,
    tool_id text,
    tool_version text,
    params jsonb,
    permission_level text,
    confirmed_by text,
    status text,
    verified boolean,
    state_change jsonb,
    retry_count integer,
    latency_ms integer,
    approval_id text,
    _batch_id text,
    _source_file text,
    _ingested_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS e0_tool_call_batch_ix ON raw.e0_tool_call (_batch_id);

CREATE TABLE IF NOT EXISTS raw.e0_approval (
    approval_id text,
    case_id text,
    requested_at timestamptz,
    requested_by_role text,
    requested_by_id text,
    tool_id text,
    params jsonb,
    reason_code text,
    policy_rule_id text,
    requester_note text,
    decided_by text,
    decided_at timestamptz,
    decision text,
    decision_note text,
    executed_call_id text,
    _batch_id text,
    _source_file text,
    _ingested_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS e0_approval_batch_ix ON raw.e0_approval (_batch_id);

CREATE TABLE IF NOT EXISTS raw.e0_case_close (
    case_id text,
    closed_at timestamptz,
    closed_by_role text,
    resolved boolean,
    contact_reason text,
    resolution_code text,
    followup_at timestamptz,
    csat integer,
    _batch_id text,
    _source_file text,
    _ingested_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS e0_case_close_batch_ix ON raw.e0_case_close (_batch_id);

CREATE TABLE IF NOT EXISTS raw.e0_signal (
    signal_id text,
    kind text,
    scope jsonb,
    window_start timestamptz,
    window_end timestamptz,
    support_cases integer,
    support_analysts integer,
    consistency text,
    evidence_case_ids jsonb,
    status text,
    _batch_id text,
    _source_file text,
    _ingested_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS e0_signal_batch_ix ON raw.e0_signal (_batch_id);

CREATE TABLE IF NOT EXISTS raw.bank_customers (
    customer_id text,
    document_number text,
    document_type text,
    first_name text,
    last_name text,
    date_of_birth date,
    gender text,
    email text,
    mobile_phone text,
    landline_phone text,
    address text,
    city text,
    state text,
    country text,
    postal_code text,
    detected_accent text,
    segment text,
    credit_score integer,
    estimated_monthly_income numeric,
    occupation text,
    marital_status text,
    education_level text,
    registration_date timestamp,
    registration_branch_id text,
    customer_status text,
    last_updated timestamp,
    accepts_marketing boolean,
    _batch_id text,
    _source_file text,
    _ingested_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS bank_customers_batch_ix ON raw.bank_customers (_batch_id);

CREATE TABLE IF NOT EXISTS raw.bank_products (
    product_id text,
    customer_id text,
    product_type text,
    product_number text,
    currency text,
    current_balance numeric,
    credit_limit numeric,
    interest_rate numeric,
    opening_date date,
    expiration_date date,
    opening_branch_id text,
    product_status text,
    opening_channel text,
    has_linked_app boolean,
    days_past_due integer,
    last_transaction_date timestamp,
    last_updated timestamp,
    _batch_id text,
    _source_file text,
    _ingested_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS bank_products_batch_ix ON raw.bank_products (_batch_id);

CREATE TABLE IF NOT EXISTS raw.bank_branches (
    branch_id text,
    branch_code text,
    branch_name text,
    branch_type text,
    address text,
    city text,
    state text,
    country text,
    postal_code text,
    geographic_zone text,
    phone text,
    email text,
    opening_time time,
    closing_time time,
    has_atms boolean,
    atm_count integer,
    has_teller_windows boolean,
    teller_window_count integer,
    latitude numeric,
    longitude numeric,
    branch_opening_date date,
    branch_status text,
    _batch_id text,
    _source_file text,
    _ingested_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS bank_branches_batch_ix ON raw.bank_branches (_batch_id);

CREATE TABLE IF NOT EXISTS raw.bank_service_agents (
    agent_id text,
    employee_code text,
    first_name text,
    last_name text,
    email text,
    phone text,
    native_accent text,
    country_of_origin text,
    assigned_branch_id text,
    agent_type text,
    experience_level text,
    languages text,
    specialty text,
    hire_date date,
    avg_csat numeric,
    total_monthly_interactions integer,
    agent_status text,
    work_shift text,
    _batch_id text,
    _source_file text,
    _ingested_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS bank_service_agents_batch_ix ON raw.bank_service_agents (_batch_id);

CREATE TABLE IF NOT EXISTS raw.bank_marketing_campaigns (
    campaign_id text,
    campaign_name text,
    description text,
    campaign_type text,
    campaign_objective text,
    promoted_product text,
    target_segment text,
    target_country text,
    start_date date,
    end_date date,
    budget numeric,
    campaign_status text,
    expected_conversion_rate numeric,
    _batch_id text,
    _source_file text,
    _ingested_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS bank_marketing_campaigns_batch_ix ON raw.bank_marketing_campaigns (_batch_id);

CREATE TABLE IF NOT EXISTS raw.bank_transactions (
    transaction_id text,
    transaction_date timestamp,
    process_date date,
    product_id text,
    customer_id text,
    transaction_type text,
    transaction_category text,
    amount numeric,
    currency text,
    amount_usd numeric,
    channel text,
    branch_id text,
    merchant_name text,
    merchant_category text,
    transaction_country text,
    transaction_city text,
    transaction_status text,
    response_code text,
    is_fraud boolean,
    fraud_score numeric,
    latitude numeric,
    longitude numeric,
    _batch_id text,
    _source_file text,
    _ingested_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS bank_transactions_batch_ix ON raw.bank_transactions (_batch_id);

CREATE TABLE IF NOT EXISTS raw.bank_call_center_interactions (
    interaction_id text,
    interaction_date timestamp,
    process_date date,
    customer_id text,
    agent_id text,
    interaction_type text,
    channel text,
    contact_reason text,
    reason_category text,
    duration_seconds integer,
    wait_time_seconds integer,
    was_resolved boolean,
    requires_followup boolean,
    detected_sentiment text,
    sentiment_score numeric,
    customer_detected_accent text,
    agent_used_accent text,
    was_escalated boolean,
    mentioned_products text,
    has_transcript boolean,
    has_recording boolean,
    _batch_id text,
    _source_file text,
    _ingested_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS bank_call_center_interactions_batch_ix ON raw.bank_call_center_interactions (_batch_id);

CREATE TABLE IF NOT EXISTS raw.bank_call_transcripts (
    transcript_id text,
    interaction_id text,
    process_date date,
    customer_id text,
    agent_id text,
    full_text text,
    customer_text text,
    agent_text text,
    detected_language text,
    detected_accent text,
    accent_confidence numeric,
    detected_keywords text,
    mentioned_entities text,
    detected_intents text,
    main_topics text,
    transcription_model text,
    audio_quality text,
    duration_seconds integer,
    _batch_id text,
    _source_file text,
    _ingested_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS bank_call_transcripts_batch_ix ON raw.bank_call_transcripts (_batch_id);

CREATE TABLE IF NOT EXISTS raw.bank_satisfaction_surveys (
    survey_id text,
    survey_date timestamp,
    process_date date,
    interaction_id text,
    customer_id text,
    agent_id text,
    survey_type text,
    send_channel text,
    main_score integer,
    nps_category text,
    question_1_text text,
    question_1_response integer,
    question_2_text text,
    question_2_response integer,
    question_3_text text,
    question_3_response integer,
    open_comments text,
    comment_sentiment text,
    response_time_hours numeric,
    campaign_response_rate numeric,
    _batch_id text,
    _source_file text,
    _ingested_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS bank_satisfaction_surveys_batch_ix ON raw.bank_satisfaction_surveys (_batch_id);

CREATE TABLE IF NOT EXISTS raw.bank_digital_events (
    event_id text,
    event_date timestamp,
    process_date date,
    customer_id text,
    session_id text,
    event_type text,
    event_category text,
    channel text,
    platform text,
    browser text,
    app_version text,
    page_url text,
    page_title text,
    action text,
    element_id text,
    product_id text,
    event_value numeric,
    duration_seconds integer,
    ip_address text,
    ip_country text,
    ip_city text,
    is_mobile boolean,
    referrer text,
    utm_source text,
    utm_medium text,
    utm_campaign text,
    _batch_id text,
    _source_file text,
    _ingested_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS bank_digital_events_batch_ix ON raw.bank_digital_events (_batch_id);

CREATE TABLE IF NOT EXISTS raw.bank_complaints (
    complaint_id text,
    creation_date timestamp,
    process_date date,
    customer_id text,
    case_type text,
    category text,
    subcategory text,
    reception_channel text,
    affected_product_id text,
    related_branch_id text,
    origin_interaction_id text,
    description text,
    claimed_amount numeric,
    currency text,
    priority text,
    status text,
    assigned_agent_id text,
    assignment_date timestamp,
    first_response_date timestamp,
    resolution_date timestamp,
    closing_date timestamp,
    sla_breached boolean,
    resolution_days integer,
    resolution text,
    compensation_granted numeric,
    resolution_satisfaction integer,
    is_repeat_complainer boolean,
    _batch_id text,
    _source_file text,
    _ingested_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS bank_complaints_batch_ix ON raw.bank_complaints (_batch_id);

CREATE TABLE IF NOT EXISTS raw.bank_campaign_sends (
    send_id text,
    send_date timestamp,
    process_date date,
    campaign_id text,
    customer_id text,
    send_channel text,
    template_used text,
    subject text,
    send_status text,
    was_delivered boolean,
    was_opened boolean,
    open_date timestamp,
    was_clicked boolean,
    click_date timestamp,
    click_count integer,
    had_conversion boolean,
    conversion_date timestamp,
    conversion_value numeric,
    open_device text,
    open_country text,
    failure_reason text,
    send_cost numeric,
    _batch_id text,
    _source_file text,
    _ingested_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS bank_campaign_sends_batch_ix ON raw.bank_campaign_sends (_batch_id);

CREATE TABLE IF NOT EXISTS raw.bank_daily_exchange_rates (
    date date,
    source_currency text,
    target_currency text,
    exchange_rate numeric,
    buy_rate numeric,
    sell_rate numeric,
    source text,
    _batch_id text,
    _source_file text,
    _ingested_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS bank_daily_exchange_rates_batch_ix ON raw.bank_daily_exchange_rates (_batch_id);
