-- GENERATED by db/gen_ddl.py from db/catalog.py. Do not edit by hand.

-- Canonical layer (dbt canonical models).

CREATE TABLE IF NOT EXISTS augmented.cases (
    case_id text,
    customer_id text,
    opened_at timestamptz,
    channel text,
    language text,
    origin text,
    topic text,
    complaint_id text,
    priority text,
    sla_due_at timestamptz,
    assigned_analyst_id text,
    source_customer_id text,
    language_source text,
    source_system text,
    _batch_id text,
    _source_file text,
    _ingested_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS cases_batch_ix ON augmented.cases (_batch_id);

CREATE TABLE IF NOT EXISTS augmented.case_closes (
    case_id text,
    closed_at timestamptz,
    closed_by_role text,
    resolved boolean,
    contact_reason text,
    resolution_code text,
    followup_at timestamptz,
    csat integer,
    csat_raw integer,
    source_system text,
    _batch_id text,
    _source_file text,
    _ingested_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS case_closes_batch_ix ON augmented.case_closes (_batch_id);

CREATE TABLE IF NOT EXISTS augmented.turns (
    turn_id text,
    case_id text,
    event_time timestamptz,
    author_role text,
    author_id text,
    text text,
    language text,
    from_suggestion_id text,
    evidence_ids jsonb,
    text_source text,
    source_system text,
    _batch_id text,
    _source_file text,
    _ingested_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS turns_batch_ix ON augmented.turns (_batch_id);

CREATE TABLE IF NOT EXISTS augmented.identity_checks (
    check_id text,
    case_id text,
    started_at timestamptz,
    ended_at timestamptz,
    actor_role text,
    actor_id text,
    channel_session text,
    questions jsonb,
    questions_version text,
    correct integer,
    result text,
    attempt integer,
    policy_rule_id text,
    trigger text,
    source_system text,
    _batch_id text,
    _source_file text,
    _ingested_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS identity_checks_batch_ix ON augmented.identity_checks (_batch_id);

CREATE TABLE IF NOT EXISTS augmented.routing_steps (
    step_id text,
    case_id text,
    event_time timestamptz,
    tier text,
    component_id text,
    component_version text,
    outcome text,
    reason_code text,
    policy_rule_id text,
    confidence double precision,
    inputs_used jsonb,
    handoff jsonb,
    source_system text,
    _batch_id text,
    _source_file text,
    _ingested_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS routing_steps_batch_ix ON augmented.routing_steps (_batch_id);

CREATE TABLE IF NOT EXISTS augmented.copilot_queries (
    query_id text,
    case_id text,
    analyst_id text,
    event_time timestamptz,
    question_text text,
    query_signature text,
    tables_read jsonb,
    columns_read jsonb,
    answered_by text,
    answer text,
    sent_to_chat boolean,
    source_system text,
    _batch_id text,
    _source_file text,
    _ingested_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS copilot_queries_batch_ix ON augmented.copilot_queries (_batch_id);

CREATE TABLE IF NOT EXISTS augmented.tool_calls (
    call_id text,
    case_id text,
    event_time timestamptz,
    actor_role text,
    actor_id text,
    tool_id text,
    tool_version text,
    params jsonb,
    permission_level text,
    confirmed_by text,
    status text,
    verified boolean,
    state_change jsonb,
    retry_count integer,
    latency_ms integer,
    approval_id text,
    source_system text,
    _batch_id text,
    _source_file text,
    _ingested_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS tool_calls_batch_ix ON augmented.tool_calls (_batch_id);

CREATE TABLE IF NOT EXISTS augmented.approvals (
    approval_id text,
    case_id text,
    requested_at timestamptz,
    requested_by_role text,
    requested_by_id text,
    tool_id text,
    params jsonb,
    reason_code text,
    policy_rule_id text,
    requester_note text,
    decided_by text,
    decided_at timestamptz,
    decision text,
    decision_note text,
    executed_call_id text,
    source_system text,
    _batch_id text,
    _source_file text,
    _ingested_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS approvals_batch_ix ON augmented.approvals (_batch_id);

CREATE TABLE IF NOT EXISTS augmented.signals (
    signal_id text,
    kind text,
    scope jsonb,
    window_start timestamptz,
    window_end timestamptz,
    support_cases integer,
    support_analysts integer,
    consistency text,
    evidence_case_ids jsonb,
    status text,
    source_system text,
    _batch_id text,
    _source_file text,
    _ingested_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS signals_batch_ix ON augmented.signals (_batch_id);
