-- GENERATED by db/gen_ddl.py from db/catalog.py. Do not edit by hand.

-- Support-platform replica, exporter allow-list columns only.

CREATE TABLE IF NOT EXISTS product.event_log (
    sequence bigint,
    event_id text,
    event_type text,
    entity text,
    entity_id text,
    case_id text,
    actor_role text,
    actor_id text,
    event_time timestamptz,
    ingested_at timestamptz,
    payload jsonb,
    tenant_id text,
    _batch_id text,
    _source_file text,
    _ingested_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS event_log_batch_ix ON product.event_log (_batch_id);

CREATE TABLE IF NOT EXISTS product.cases (
    id text,
    customer_id text,
    channel text,
    language text,
    priority text,
    opened_at timestamptz,
    sla_due_at timestamptz,
    previous_case_id text,
    rating_score integer,
    rated_at timestamptz,
    tenant_id text,
    _batch_id text,
    _source_file text,
    _ingested_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS cases_batch_ix ON product.cases (_batch_id);

CREATE TABLE IF NOT EXISTS product.customers (
    id text,
    simulator boolean,
    _batch_id text,
    _source_file text,
    _ingested_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS customers_batch_ix ON product.customers (_batch_id);

CREATE TABLE IF NOT EXISTS product.staff (
    id text,
    roles jsonb,
    languages jsonb,
    team text,
    team_id text,
    active boolean,
    _batch_id text,
    _source_file text,
    _ingested_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS staff_batch_ix ON product.staff (_batch_id);

CREATE TABLE IF NOT EXISTS product.turns (
    id text,
    case_id text,
    sequence integer,
    kind text,
    audience text,
    author_role text,
    created_at timestamptz,
    _batch_id text,
    _source_file text,
    _ingested_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS turns_batch_ix ON product.turns (_batch_id);

CREATE TABLE IF NOT EXISTS product.assignments (
    id text,
    case_id text,
    staff_id text,
    reason text,
    policy_rule_id text,
    strategy text,
    open_cases_at_assignment integer,
    waited_seconds integer,
    previous_staff_id text,
    paused_override boolean,
    assigned_at timestamptz,
    _batch_id text,
    _source_file text,
    _ingested_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS assignments_batch_ix ON product.assignments (_batch_id);

CREATE TABLE IF NOT EXISTS product.customer_case_slots (
    customer_id text,
    open_case_id text,
    _batch_id text,
    _source_file text,
    _ingested_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS customer_case_slots_batch_ix ON product.customer_case_slots (_batch_id);

CREATE UNIQUE INDEX IF NOT EXISTS event_log_sequence_ux ON product.event_log (sequence);
-- watermark: the monitor reads event_log WHERE sequence > :last ORDER BY sequence.
