"""M1 generators: real llm-gateway in the local Core stack (pure stdlib). Emits env references only, never values."""

from __future__ import annotations

import json
from pathlib import Path

GATEWAY_SHA = "63155b600d4b108ac871125cfd633c2beb11b0b5"  # llm-gateway main (docs/reports/gates/facts.json)
GATEWAY_REPO = "https://github.com/pulso-factored/llm-gateway.git"
ALIAS = "pulso-evolution-llm"
MODEL = "external-reasoning-model"
PRICE = {"input_per_mtok": "1", "output_per_mtok": "4"}  # matches the registry profile; registry untouched
SHIM_URL = "http://roleplay-llm:8640/v1"
HERE = Path(__file__).resolve().parent


def llm_endpoints() -> dict:
    return {ALIAS: {"base_url": SHIM_URL, "api_key_env": "ROLEPLAY_LLM_API_KEY"}}


def gateway_consumers() -> dict:
    return {"pulso-core": {"token_env": "GATEWAY_TOKEN_PULSO_CORE"}}


def generate_profile() -> dict:
    return {"endpoint_alias": ALIAS, "model": MODEL, "price": dict(PRICE)}


def env_template() -> str:
    return "\n".join([
        "# Generated by gen_gateway.py. Secrets are only named; fill the empty variables in the git-ignored env file.",
        f"GATEWAY_CONSUMERS='{json.dumps(gateway_consumers(), separators=(',', ':'))}'",
        "GATEWAY_TOKEN_PULSO_CORE=",
        f"LLM_ENDPOINTS='{json.dumps(llm_endpoints(), separators=(',', ':'))}'",
        "ROLEPLAY_LLM_API_KEY=",
        "",
    ])


def gateway_double(image_present: bool) -> str:
    """Line for engine-run doubles[]: the contract double answers when the Go image is absent."""
    return f"gateway=real@{GATEWAY_SHA[:12]}" if image_present else "gateway=stand-in"


def overlay_yaml() -> str:
    return f"""# Generated by gen_gateway.py (do not edit). Overlay for compose.core.yaml + compose.gateway.yaml.
# Gateway and shim sit on the internal network only: no host ports, no route out, secrets by reference.
services:
  llm-gateway:
    build:
      context: {GATEWAY_REPO}#{GATEWAY_SHA}
    networks: [pulso-gw-e0]
    environment:
      GATEWAY_CONSUMERS: ${{GATEWAY_CONSUMERS:?set}}
      GATEWAY_TOKEN_PULSO_CORE: ${{GATEWAY_TOKEN_PULSO_CORE:?set}}
      LLM_ENDPOINTS: ${{LLM_ENDPOINTS:?set}}
      ROLEPLAY_LLM_API_KEY: ${{ROLEPLAY_LLM_API_KEY:?set}}
    depends_on: [roleplay-llm]
    healthcheck:
      test: ["CMD", "/llm-gateway", "-healthcheck"]
      interval: 5s
      retries: 12
  roleplay-llm:
    image: ${{PULSO_ROLEPLAY_LLM_IMAGE:-localhost/pulso-roleplay-llm:unset}}
    command: ["python", "-m", "roleplay_llm", "--queue", "/queue", "--host", "0.0.0.0", "--port", "8640"]
    networks: [pulso-gw-e0]
networks:
  pulso-gw-e0:
    internal: true
"""


if __name__ == "__main__":
    (HERE / "compose.gateway-real.yaml").write_text(overlay_yaml(), encoding="utf-8", newline="\n")
    (HERE / "gateway.env.example").write_text(env_template(), encoding="utf-8", newline="\n")
