// @generated by gen/gen_tables.py from bridge-contract/contract.json + core-bridge ADR 0012. Do not edit.
use crate::errors::{Disposition, ErrorKind, Kind};

pub const AGENT_CORE_SHA: &str = "c814c2bad9f154d10c092326558815dca9562be7";
pub const CONTRACTS_VERSION: &str = "1.3.0";
pub const MANIFEST_SHA256: &str = "68f335f27cae0fa713c90537066bdc1d88b595e417312f75ca1cb967bffb876a";
pub const BASE_PATH: &str = "/internal/v1";
pub const CONTRACT_REVISION: &str = "pulso-two-teams-1";
pub const JWT_ISS: &str = "control-api";
pub const JWT_AUD: &str = "core-bridge";
pub const JWT_MAX_TTL_SECONDS: i64 = 300;

pub const TABLE: &[ErrorKind] = &[
    ErrorKind { code: "pulso:admission_attempt_mismatch", kind: Kind::Denied, retryable: false, disposition: Disposition::Terminal, statuses: &[403] },
    ErrorKind { code: "pulso:admission_cross_tenant", kind: Kind::Denied, retryable: false, disposition: Disposition::Terminal, statuses: &[403] },
    ErrorKind { code: "pulso:admission_expired", kind: Kind::Conflict, retryable: false, disposition: Disposition::Terminal, statuses: &[409] },
    ErrorKind { code: "pulso:admission_missing", kind: Kind::Denied, retryable: false, disposition: Disposition::Terminal, statuses: &[403] },
    ErrorKind { code: "pulso:admission_not_admitted", kind: Kind::Conflict, retryable: false, disposition: Disposition::Terminal, statuses: &[409] },
    ErrorKind { code: "pulso:admission_proposal_mismatch", kind: Kind::Denied, retryable: false, disposition: Disposition::Terminal, statuses: &[403] },
    ErrorKind { code: "pulso:alias_unknown", kind: Kind::NotFound, retryable: false, disposition: Disposition::Terminal, statuses: &[404] },
    ErrorKind { code: "pulso:auth_denied", kind: Kind::Auth, retryable: false, disposition: Disposition::Terminal, statuses: &[403] },
    ErrorKind { code: "pulso:auth_invalid", kind: Kind::Auth, retryable: false, disposition: Disposition::Terminal, statuses: &[401] },
    ErrorKind { code: "pulso:base_release_unknown", kind: Kind::NotFound, retryable: false, disposition: Disposition::Terminal, statuses: &[404] },
    ErrorKind { code: "pulso:binding_not_confirmed", kind: Kind::Denied, retryable: false, disposition: Disposition::Terminal, statuses: &[403] },
    ErrorKind { code: "pulso:bridge_busy", kind: Kind::Capacity, retryable: true, disposition: Disposition::Retry, statuses: &[429] },
    ErrorKind { code: "pulso:broker_denied", kind: Kind::Denied, retryable: false, disposition: Disposition::Terminal, statuses: &[403] },
    ErrorKind { code: "pulso:budget_unknown", kind: Kind::Denied, retryable: false, disposition: Disposition::Terminal, statuses: &[403] },
    ErrorKind { code: "pulso:canary_detected", kind: Kind::Invalid, retryable: false, disposition: Disposition::Terminal, statuses: &[422] },
    ErrorKind { code: "pulso:candidate_changed", kind: Kind::Conflict, retryable: false, disposition: Disposition::Terminal, statuses: &[409] },
    ErrorKind { code: "pulso:core_unavailable", kind: Kind::Unavailable, retryable: true, disposition: Disposition::Retry, statuses: &[503] },
    ErrorKind { code: "pulso:credential_not_issuable", kind: Kind::Denied, retryable: false, disposition: Disposition::Terminal, statuses: &[403] },
    ErrorKind { code: "pulso:credential_signing_unavailable", kind: Kind::Unavailable, retryable: true, disposition: Disposition::Retry, statuses: &[503] },
    ErrorKind { code: "pulso:digest_conflict", kind: Kind::Conflict, retryable: false, disposition: Disposition::Terminal, statuses: &[409] },
    ErrorKind { code: "pulso:dry_run_unavailable", kind: Kind::Unavailable, retryable: true, disposition: Disposition::Retry, statuses: &[503] },
    ErrorKind { code: "pulso:evaluate_disabled", kind: Kind::Denied, retryable: false, disposition: Disposition::Terminal, statuses: &[403] },
    ErrorKind { code: "pulso:evaluation_attempt_exists", kind: Kind::Conflict, retryable: false, disposition: Disposition::Terminal, statuses: &[409] },
    ErrorKind { code: "pulso:evaluation_context_invalid", kind: Kind::Invalid, retryable: false, disposition: Disposition::Terminal, statuses: &[422] },
    ErrorKind { code: "pulso:evaluation_context_missing", kind: Kind::Denied, retryable: false, disposition: Disposition::Terminal, statuses: &[403] },
    ErrorKind { code: "pulso:evaluation_in_progress", kind: Kind::Conflict, retryable: true, disposition: Disposition::Retry, statuses: &[409] },
    ErrorKind { code: "pulso:evaluation_unknown", kind: Kind::Conflict, retryable: false, disposition: Disposition::Terminal, statuses: &[409] },
    ErrorKind { code: "pulso:fact_schema_violation", kind: Kind::Invalid, retryable: false, disposition: Disposition::Terminal, statuses: &[422] },
    ErrorKind { code: "pulso:http_error", kind: Kind::Invalid, retryable: false, disposition: Disposition::Terminal, statuses: &[405] },
    ErrorKind { code: "pulso:idempotency_conflict", kind: Kind::Conflict, retryable: false, disposition: Disposition::Terminal, statuses: &[409] },
    ErrorKind { code: "pulso:idempotency_key_invalid", kind: Kind::Invalid, retryable: false, disposition: Disposition::Terminal, statuses: &[422] },
    ErrorKind { code: "pulso:input_too_large", kind: Kind::Invalid, retryable: false, disposition: Disposition::Terminal, statuses: &[413] },
    ErrorKind { code: "pulso:internal_error", kind: Kind::Internal, retryable: true, disposition: Disposition::Retry, statuses: &[500] },
    ErrorKind { code: "pulso:invalid_request", kind: Kind::Invalid, retryable: false, disposition: Disposition::Terminal, statuses: &[422] },
    ErrorKind { code: "pulso:mixed_world_rejected", kind: Kind::Conflict, retryable: false, disposition: Disposition::Terminal, statuses: &[409] },
    ErrorKind { code: "pulso:not_found", kind: Kind::NotFound, retryable: false, disposition: Disposition::Terminal, statuses: &[404] },
    ErrorKind { code: "pulso:not_implemented", kind: Kind::Internal, retryable: false, disposition: Disposition::Terminal, statuses: &[501] },
    ErrorKind { code: "pulso:output_missing", kind: Kind::Invalid, retryable: false, disposition: Disposition::Terminal, statuses: &[422] },
    ErrorKind { code: "pulso:output_too_large", kind: Kind::Invalid, retryable: false, disposition: Disposition::Terminal, statuses: &[413] },
    ErrorKind { code: "pulso:payload_too_large", kind: Kind::Invalid, retryable: false, disposition: Disposition::Terminal, statuses: &[413] },
    ErrorKind { code: "pulso:proposal_not_found", kind: Kind::NotFound, retryable: false, disposition: Disposition::Terminal, statuses: &[404] },
    ErrorKind { code: "pulso:release_drift", kind: Kind::Conflict, retryable: false, disposition: Disposition::Terminal, statuses: &[409] },
    ErrorKind { code: "pulso:release_pin_unavailable", kind: Kind::Conflict, retryable: false, disposition: Disposition::Terminal, statuses: &[409] },
    ErrorKind { code: "pulso:release_revoked", kind: Kind::Conflict, retryable: false, disposition: Disposition::Terminal, statuses: &[409] },
    ErrorKind { code: "pulso:release_settings_not_allowed", kind: Kind::Invalid, retryable: false, disposition: Disposition::Terminal, statuses: &[422] },
    ErrorKind { code: "pulso:run_not_found", kind: Kind::NotFound, retryable: false, disposition: Disposition::Terminal, statuses: &[404] },
    ErrorKind { code: "pulso:sandbox_required", kind: Kind::Conflict, retryable: false, disposition: Disposition::Terminal, statuses: &[409] },
    ErrorKind { code: "pulso:stage_agent_mismatch", kind: Kind::Invalid, retryable: false, disposition: Disposition::Terminal, statuses: &[422] },
    ErrorKind { code: "pulso:stage_unknown", kind: Kind::Invalid, retryable: false, disposition: Disposition::Terminal, statuses: &[400] },
    ErrorKind { code: "pulso:suite_mismatch", kind: Kind::Conflict, retryable: false, disposition: Disposition::Terminal, statuses: &[409] },
    ErrorKind { code: "pulso:supersedes_invalid", kind: Kind::Conflict, retryable: false, disposition: Disposition::Terminal, statuses: &[409] },
    ErrorKind { code: "pulso:task_in_progress", kind: Kind::Progress, retryable: false, disposition: Disposition::Terminal, statuses: &[200] },
    ErrorKind { code: "pulso:task_unknown", kind: Kind::Progress, retryable: false, disposition: Disposition::Terminal, statuses: &[200] },
    ErrorKind { code: "pulso:tenant_mismatch", kind: Kind::Denied, retryable: false, disposition: Disposition::Terminal, statuses: &[403] },
    ErrorKind { code: "pulso:unknown_input_slot", kind: Kind::Invalid, retryable: false, disposition: Disposition::Terminal, statuses: &[400] },
];

pub const AUTH_REASONS: &[(&str, u16)] = &[
    ("missing_token", 401),
    ("malformed", 401),
    ("bad_header", 401),
    ("unknown_kid", 401),
    ("bad_signature", 401),
    ("key_binding", 401),
    ("wrong_audience", 401),
    ("missing_claims", 401),
    ("expired", 401),
    ("ttl_too_long", 401),
    ("tenant_required", 403),
    ("purpose_denied", 403),
    ("sub_not_worker", 403),
    ("job_mismatch", 403),
    ("jti_replayed", 401),
];
